version: "3.9"
   
services:
  db:
    image: mysql
    volumes:
      - ./NCARDDatabase/secrets:/secrets
      - db_data:/var/lib/mysql
    environment:
      - MYSQL_RANDOM_ROOT_PASSWORD=yes
      - MYSQL_DATABASE=ncarddb
      - MYSQL_USER=ncarddb
      - MYSQL_PASSWORD_FILE=/secrets/db_password.txt
  web:
    build: .
    volumes:
      - .:/code
    ports:
      - "80:80"
      - "443:443"
    environment:
      - MYSQL_DATABASE=ncarddb
      - MYSQL_USER=ncarddb
    depends_on:
      - db
  certbot:
    image: certbot/certbot:latest
    volumes:
      - ./certbot/www:/var/www/certbot:rw
      - ./certbot/conf:/etc/letsencrypt:rw
volumes:
  db_data:
