# Generated by Django 4.1 on 2022-11-03 07:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ncard_app', '0044_alter_publication_source_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='person',
            name='active',
            field=models.IntegerField(choices=[(0, 'No'), (1, 'Yes')], default=1, verbose_name='Active'),
        ),
    ]
