# Generated by Django 4.1.4 on 2022-12-20 06:18

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('ncard_app', '0045_create_admin_user'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='students',
            options={'ordering': ['student_name'], 'verbose_name_plural': 'Students'},
        ),
    ]
