# Generated by Django 4.1 on 2022-11-03 08:25

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('ncard_app', '0045_person_active'),
    ]

    operations = [
        migrations.AddField(
            model_name='organisation',
            name='org_country',
            field=models.ForeignKey(default='AU', on_delete=django.db.models.deletion.RESTRICT, related_name='+', to='ncard_app.country', verbose_name='Country'),
        ),
        migrations.AddField(
            model_name='organisation',
            name='org_line1',
            field=models.CharField(blank=True, max_length=64, null=True, verbose_name='Line 1'),
        ),
        migrations.AddField(
            model_name='organisation',
            name='org_line2',
            field=models.CharField(blank=True, max_length=64, null=True, verbose_name='Line 2'),
        ),
        migrations.AddField(
            model_name='organisation',
            name='org_line3',
            field=models.CharField(blank=True, max_length=64, null=True, verbose_name='Line 3'),
        ),
        migrations.AddField(
            model_name='organisation',
            name='org_postcode',
            field=models.CharField(blank=True, max_length=20, null=True, verbose_name='Postcode'),
        ),
        migrations.AddField(
            model_name='organisation',
            name='org_state',
            field=models.CharField(blank=True, max_length=3, null=True, verbose_name='State (abbrev.)'),
        ),
        migrations.AddField(
            model_name='organisation',
            name='org_suburb',
            field=models.CharField(blank=True, max_length=32, null=True, verbose_name='Suburb'),
        ),
    ]
