# Generated by Django 4.1.4 on 2022-12-20 08:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ncard_app', '0046_alter_students_options'),
    ]

    operations = [
        migrations.AlterField(
            model_name='person',
            name='research_focus',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='Research Focus'),
        ),
    ]
