# Generated by Django 4.1.5 on 2023-01-09 06:36

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ncard_app', '0047_alter_person_research_focus'),
    ]

    operations = [
        migrations.AlterField(
            model_name='award',
            name='notes',
            field=models.TextField(blank=True, default='', verbose_name='notes'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='event',
            name='detail',
            field=models.TextField(blank=True, default='', verbose_name='details'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='event',
            name='event_type',
            field=models.CharField(blank=True, default='', max_length=255, verbose_name='type'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='event',
            name='location',
            field=models.CharField(blank=True, default='', max_length=255, verbose_name='location'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='event',
            name='number_attendees',
            field=models.TextField(blank=True, default='', verbose_name='number of Attendees'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='event',
            name='participants',
            field=models.TextField(blank=True, default='', verbose_name='participants'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='event',
            name='title',
            field=models.CharField(blank=True, default='', max_length=255, verbose_name='Title'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='organisation',
            name='phone',
            field=models.CharField(blank=True, default='', max_length=25, validators=[django.core.validators.RegexValidator('^[ 0-9()+,*#-]*$', 'Phone numbers must contain only these characters: #()*+,-0123456789')], verbose_name='phone'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='organisation',
            name='twitter_handle',
            field=models.CharField(blank=True, default='', max_length=16, validators=[django.core.validators.RegexValidator('^$|^@[A-Za-z0-9_]+$', 'Twitter handle must begin with an @ and only contain letters, digits and underscores.')], verbose_name='Twitter Handle'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='person',
            name='cre_role',
            field=models.CharField(blank=True, default='', max_length=15, verbose_name='CRE Role'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='person',
            name='home_line1',
            field=models.CharField(blank=True, default='', max_length=64, verbose_name='Line 1'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='person',
            name='home_line2',
            field=models.CharField(blank=True, default='', max_length=64, verbose_name='Line 2'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='person',
            name='home_line3',
            field=models.CharField(blank=True, default='', max_length=64, verbose_name='Line 3'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='person',
            name='home_postcode',
            field=models.CharField(blank=True, default='', max_length=20, verbose_name='Postcode'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='person',
            name='home_state',
            field=models.CharField(blank=True, default='', max_length=3, verbose_name='State (abbrev.)'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='person',
            name='home_suburb',
            field=models.CharField(blank=True, default='', max_length=32, verbose_name='Suburb'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='person',
            name='location',
            field=models.CharField(blank=True, default='', max_length=50),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='person',
            name='middle_name',
            field=models.CharField(blank=True, default='', max_length=64, verbose_name='Middle Name'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='person',
            name='notes',
            field=models.TextField(blank=True, default=''),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='person',
            name='orcid_id',
            field=models.CharField(blank=True, default='', max_length=37, validators=[django.core.validators.RegexValidator('^$|^https://orcid\\.org/\\d{4}-\\d{4}-\\d{4}-\\d{3}(\\d|X)$', 'ORCID identifier must be a full URL, in this format: https://orcid.org/XXXX-XXXX-XXXX-XXXX')], verbose_name='ORCID iD'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='person',
            name='phone_home',
            field=models.CharField(blank=True, default='', max_length=25, validators=[django.core.validators.RegexValidator('^[ 0-9()+,*#-]*$', 'Phone numbers must contain only these characters: #()*+,-0123456789')], verbose_name='phone (Home)'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='person',
            name='phone_mobile',
            field=models.CharField(blank=True, default='', max_length=25, validators=[django.core.validators.RegexValidator('^[ 0-9()+,*#-]*$', 'Phone numbers must contain only these characters: #()*+,-0123456789')], verbose_name='phone (Mobile)'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='person',
            name='phone_office',
            field=models.CharField(blank=True, default='', max_length=25, validators=[django.core.validators.RegexValidator('^[ 0-9()+,*#-]*$', 'Phone numbers must contain only these characters: #()*+,-0123456789')], verbose_name='phone (Office)'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='person',
            name='profile_url',
            field=models.URLField(blank=True, default='', verbose_name='Profile URL'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='person',
            name='project',
            field=models.CharField(blank=True, default='', max_length=50),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='person',
            name='research_focus',
            field=models.CharField(blank=True, default='', max_length=255, verbose_name='Research Focus'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='person',
            name='surname',
            field=models.CharField(default='', max_length=64, verbose_name='Last Name'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='person',
            name='title',
            field=models.CharField(blank=True, default='', max_length=16),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='person',
            name='twitter',
            field=models.CharField(blank=True, default='', max_length=16, validators=[django.core.validators.RegexValidator('^$|^@[A-Za-z0-9_]+$', 'Twitter handle must begin with an @ and only contain letters, digits and underscores.')], verbose_name='Twitter Handle'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='person',
            name='work_line1',
            field=models.CharField(blank=True, default='', max_length=64, verbose_name='Line 1'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='person',
            name='work_line2',
            field=models.CharField(blank=True, default='', max_length=64, verbose_name='Line 2'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='person',
            name='work_line3',
            field=models.CharField(blank=True, default='', max_length=64, verbose_name='Line 3'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='person',
            name='work_postcode',
            field=models.CharField(blank=True, default='', max_length=20, verbose_name='Postcode'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='person',
            name='work_state',
            field=models.CharField(blank=True, default='', max_length=3, verbose_name='State (abbrev.)'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='person',
            name='work_suburb',
            field=models.CharField(blank=True, default='', max_length=32, verbose_name='Suburb'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='person',
            name='wos_researcher_id',
            field=models.CharField(blank=True, default='', max_length=32, verbose_name='WoS ResearcherID'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='publication',
            name='page_end',
            field=models.CharField(blank=True, default='', max_length=255, verbose_name='end page'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='publication',
            name='page_start',
            field=models.CharField(blank=True, default='', max_length=255, verbose_name='start page'),
            preserve_default=False,
        ),
    ]
