# Generated by Django 4.1.5 on 2023-01-10 05:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ncard_app', '0048_alter_award_notes_alter_event_detail_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='person',
            name='active',
            field=models.BooleanField(default=True, verbose_name='Active'),
        ),
        migrations.AddField(
            model_name='students',
            name='active_student',
            field=models.BooleanField(default=True, verbose_name='Active'),
        ),
        migrations.AddField(
            model_name='students',
            name='notes',
            field=models.TextField(blank=True, verbose_name='notes'),
        ),
        migrations.AlterField(
            model_name='students',
            name='student_type',
            field=models.IntegerField(choices=[(1, 'PhD'), (2, 'Honours'), (3, 'Masters'), (4, 'Clinical Research Fellow'), (5, 'Medical Fellow'), (6, 'MBBS'), (7, 'Other (please specify)')], verbose_name='Student Type'),
        ),
    ]
