# Generated by Django 4.1.5 on 2023-01-10 06:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ncard_app', '0049_person_active_students_active_student_students_notes_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='event',
            name='number_attendees',
            field=models.CharField(blank=True, max_length=255, verbose_name='number of Attendees'),
        ),
    ]
