# Generated by Django 4.1.5 on 2023-01-10 07:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ncard_app', '0050_alter_event_number_attendees'),
    ]

    operations = [
        migrations.AlterField(
            model_name='person',
            name='active',
            field=models.BooleanField(default=False, verbose_name='Active'),
        ),
        migrations.AlterField(
            model_name='students',
            name='active_student',
            field=models.BooleanField(default=False, verbose_name='Active'),
        ),
    ]
