# Generated by Django 4.1.5 on 2023-01-10 07:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ncard_app', '0052_remove_person_active_remove_students_active_student'),
    ]

    operations = [
        migrations.AddField(
            model_name='person',
            name='active',
            field=models.BooleanField(default=True, verbose_name='Active'),
        ),
        migrations.AddField(
            model_name='students',
            name='active_student',
            field=models.BooleanField(default=True, verbose_name='Active'),
        ),
    ]
