# Generated by Django 4.1.5 on 2023-01-16 06:41

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('ncard_app', '0058_alter_person_active_alter_students_active_student'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='person',
            options={'ordering': ['surname', 'given_name', 'id'], 'verbose_name_plural': 'People'},
        ),
    ]
