# Generated by Django 4.1.5 on 2023-01-17 05:28

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('ncard_app', '0060_alter_grant_title'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='award',
            name='notes',
        ),
    ]
