# Generated by Django 4.1.5 on 2023-01-17 05:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ncard_app', '0061_remove_award_notes'),
    ]

    operations = [
        migrations.AlterField(
            model_name='award',
            name='no_year',
            field=models.DecimalField(blank=True, decimal_places=1, default=0.0, max_digits=10, null=True, verbose_name='Concurrent Years'),
        ),
    ]
