# Generated by Django 4.1.5 on 2023-01-17 08:47

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('ncard_app', '0063_alter_award_no_year'),
    ]

    operations = [
        migrations.RenameField(
            model_name='grant',
            old_name='reference',
            new_name='grant_reference',
        ),
        migrations.AddField(
            model_name='grant',
            name='agency',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='grants', to='ncard_app.organisation'),
        ),
        migrations.AddField(
            model_name='grant',
            name='bu_no',
            field=models.CharField(blank=True, max_length=64, verbose_name='Business Unit Number'),
        ),
        migrations.AddField(
            model_name='grant',
            name='pg_no',
            field=models.CharField(blank=True, max_length=64, verbose_name='PG Number'),
        ),
        migrations.AddField(
            model_name='grant',
            name='roap_reference',
            field=models.CharField(blank=True, max_length=64),
        ),
        migrations.AddField(
            model_name='grant',
            name='status',
            field=models.IntegerField(blank=True, choices=[(1, 'Application submitted'), (2, 'Grant unsuccessful'), (3, 'Current'), (4, 'Complete')], default=1, null=True, verbose_name='type'),
        ),
        migrations.AddField(
            model_name='grant',
            name='total_award',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=15, null=True, verbose_name='Total Amount Awarded'),
        ),
        migrations.AddField(
            model_name='grant',
            name='total_request',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=15, null=True, verbose_name='Total Amount Requested'),
        ),
        migrations.AddField(
            model_name='grant',
            name='year_end',
            field=models.PositiveSmallIntegerField(blank=True, null=True, verbose_name='Year End'),
        ),
        migrations.AddField(
            model_name='grant',
            name='year_start',
            field=models.PositiveSmallIntegerField(blank=True, null=True, verbose_name='Year Start'),
        ),
        migrations.AddField(
            model_name='grant',
            name='year_submitted',
            field=models.PositiveSmallIntegerField(blank=True, null=True, verbose_name='Year Submitted'),
        ),
        migrations.AlterField(
            model_name='award',
            name='award_type',
            field=models.IntegerField(blank=True, choices=[(1, 'Prize'), (2, 'Scholarship'), (3, 'Award')], null=True, verbose_name='type'),
        ),
    ]
