# Generated by Django 4.1.5 on 2023-01-18 03:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ncard_app', '0065_alter_grant_grant_reference_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='person',
            name='project',
        ),
        migrations.AddField(
            model_name='person',
            name='project',
            field=models.ManyToManyField(blank=True, related_name='team', to='ncard_app.project'),
        ),
    ]
