# Generated by Django 4.1.5 on 2023-01-18 03:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ncard_app', '0066_remove_person_project_person_project'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='students',
            name='scholarship',
        ),
        migrations.AlterField(
            model_name='students',
            name='supervisor',
            field=models.ManyToManyField(blank=True, related_name='students', to='ncard_app.person'),
        ),
        migrations.AddField(
            model_name='students',
            name='scholarship',
            field=models.ManyToManyField(blank=True, related_name='award', to='ncard_app.award'),
        ),
    ]
