# Generated by Django 4.1.5 on 2023-01-19 05:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ncard_app', '0069_alter_grant_bu_no_alter_grant_pg_no'),
    ]

    operations = [
        migrations.AddField(
            model_name='publication',
            name='issue',
            field=models.PositiveSmallIntegerField(blank=True, null=True, verbose_name='issue'),
        ),
        migrations.AlterField(
            model_name='publication',
            name='doi',
            field=models.CharField(max_length=255, verbose_name='DOI'),
        ),
    ]
