# Generated by Django 4.1.5 on 2023-01-19 08:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ncard_app', '0070_publication_issue_alter_publication_doi'),
    ]

    operations = [
        migrations.AlterField(
            model_name='grant',
            name='status',
            field=models.IntegerField(blank=True, choices=[(1, 'Application submitted'), (2, 'Unsuccessful'), (3, 'Current'), (4, 'Complete')], default=1, null=True, verbose_name='Status'),
        ),
    ]
