# Generated by Django 4.1.10 on 2023-07-17 08:36

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('ncard_app', '0071_alter_grant_status'),
    ]

    operations = [
        migrations.CreateModel(
            name='Department',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, verbose_name='name')),
                ('org', models.ForeignKey(on_delete=django.db.models.deletion.RESTRICT, related_name='org_depts', to='ncard_app.organisation')),
            ],
            options={
                'db_table': 'Department',
                'ordering': ['name', 'org'],
            },
        ),
        migrations.AddField(
            model_name='person',
            name='department_other',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='contacts_other_dept', to='ncard_app.department'),
        ),
        migrations.AddField(
            model_name='person',
            name='department_primary',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='contacts_primary_dept', to='ncard_app.department'),
        ),
    ]
