# Generated by Django 4.1.10 on 2023-07-18 09:21

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('ncard_app', '0073_alter_person_department_other_and_more'),
    ]

    operations = [
        migrations.RenameIndex(
            model_name='person',
            new_name='person_surname_b68bb2_idx',
            old_name='Person_surname_2b0d3e_idx',
        ),
        migrations.RenameIndex(
            model_name='person',
            new_name='person_given_n_576f78_idx',
            old_name='Person_given_n_55be79_idx',
        ),
        migrations.RenameIndex(
            model_name='project',
            new_name='project_name_f50fde_idx',
            old_name='Project_name_f73564_idx',
        ),
        migrations.AlterModelTable(
            name='award',
            table='award',
        ),
        migrations.AlterModelTable(
            name='country',
            table='country',
        ),
        migrations.AlterModelTable(
            name='department',
            table='department',
        ),
        migrations.AlterModelTable(
            name='event',
            table='event',
        ),
        migrations.AlterModelTable(
            name='grant',
            table='grant',
        ),
        migrations.AlterModelTable(
            name='grantinvestigator',
            table='grantinvestigator',
        ),
        migrations.AlterModelTable(
            name='organisation',
            table='organisation',
        ),
        migrations.AlterModelTable(
            name='person',
            table='person',
        ),
        migrations.AlterModelTable(
            name='project',
            table='project',
        ),
        migrations.AlterModelTable(
            name='publication',
            table='publication',
        ),
        migrations.AlterModelTable(
            name='students',
            table='student',
        ),
    ]
